services:
  zpush:
    build: .
    ports:
      - "8880:80"
    volumes:
      - ./z-push/z-push.conf.php:/etc/z-push/z-push.conf.php
      - ./z-push/imap.conf.php:/etc/z-push/imap.conf.php
    restart: unless-stopped
