services:
  zpush:
    build: .
    ports:
      - "8880:80"
    volumes:
      - ./z-push/z-push.conf.php:/etc/z-push/z-push.conf.php
      - ./z-push/imap.conf.php:/etc/z-push/imap.conf.php
      - ./z-push/caldav.conf.php:/etc/z-push/caldav.conf.php
      - ./z-push/carddav.conf.php:/etc/z-push/carddav.conf.php
    # restart: unless-stopped
