server {
    listen 80;
    server_name _;

    root /usr/share/z-push;
    index index.php;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    location /autodiscover/autodiscover.xml {
        root /usr/share/z-push;
        index autodiscover.php;
        try_files $uri =404;
        fastcgi_pass unix:/var/run/php/php-fpm.sock;
        fastcgi_index autodiscover.php;
        fastcgi_param SCRIPT_FILENAME $document_root/autodiscover.php;
        include fastcgi_params;
    }

}
